version: '3.8'

networks:
  rete-laboratorio:
    driver: bridge

volumes:
  db_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local

services:
  # 1. DATABASE: MariaDB
  mariadb_servizio:
    image: mariadb:11.2
    container_name: mariadb_container
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - rete-laboratorio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: azienda_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. INTERFACCIA WEB DB: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped
    networks:
      - rete-laboratorio
    environment:
      PMA_HOST: mariadb_servizio
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      mariadb_servizio:
        condition: service_healthy

  # 3. BACKEND: Spring Boot
  backend:
    build: ./backend
    container_name: spring_backend_container
    restart: unless-stopped
    networks:
      - rete-laboratorio
    expose:
      - "8095"
    depends_on:
      mariadb_servizio:
        condition: service_healthy

  # 4. FRONTEND: Torna ad essere un semplice Nginx statico sulla rete interna
  frontend:
    image: nginx:latest
    container_name: nginx_frontend_container
    restart: unless-stopped
    networks:
      - rete-laboratorio
    expose:
      - "80" # Blindato internamente, ci penserà NPM a parlargli
    volumes:
      - ./frontend:/usr/share/nginx/html

  # 5. REVERSE PROXY MANAGER (Il nuovo regista)
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'    # Traffico HTTP pubblico
      - '443:443'  # Traffico HTTPS pubblico
      - '81:81'    # Interfaccia Web di Amministrazione di NPM
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - rete-laboratorio
    depends_on:
      - frontend
      - backend