spring.application.name=demoRestful

server.port=8095

spring.datasource.url=jdbc:mariadb://mariadb_servizio/azienda_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configurazione Hibernate (DDL Auto)
# 'update' istruisce Hibernate a creare automaticamente le tabelle se mancano o aggiornarle
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL generate da Hibernate nel terminale (ottimo per il debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
